### PR TITLE
Use C interface to get constraint dimension

### PR DESCRIPTION
**Pull request by FreyJo**

### CODE REVIEW

**Comment by adrian-kriegel** [comment]
Thanks for the PR. I can't find any doc on `ocp_nlp_dims_get_from_attr` but I know that you know what you are doing :-)

**Comment by adrian-kriegel** [comment]
Sorry, the change does not compile (missing semicolon). But even with the semicolon, the tests don't pass.

``error: ocp_nlp_dims_get_from_attr: field nbx not available``

**Comment by FreyJo** [comment]
Hi,
Sorry for the missing semicolon and not testing it.
I just wanted to point out that the code in place is not the C interface of acados but rather part of the core.
The function does expect the name of a numerical array to be set, like `lbx`.
We could add the names of dimensions in that function as well.

**Comment by adrian-kriegel** [comment]
It turns out that the way I did it (which mirrors the way ACADOS does it internally) can lead to undefined behavior. It's a little difficult to test due to that. It's honestly not worth keeping the API backwards compatible, so I included your solution in the latest update. 
Existing code that still uses get_constraint_dims(n, "nbx") will now at least provoke a run time exception: "field nbx not available". 

New syntax is: ```get_constraint_dims(n, "lbx")``` ```get_constraint_dims(n, "ubx")``` for lower and upper bounds respectively.

Thanks!

**Pull request merged**
